services:
  - type: web
    name: flask-backend
    env: python
    pythonVersion: 3.10
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon

  - type: web
    name: react-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    plan: free
    region: oregon
